Repository RabbitHoleRP/RedisLib, pull requests merged in 2023-07, with the labels that each got.

#19 Add english translations
  src/main/java/br/com/rabbithole/RedisLib.java
  src/main/java/br/com/rabbithole/configurations/RedisConfig.java
  src/main/java/br/com/rabbithole/core/builder/base/Command.java
  src/main/java/br/com/rabbithole/core/builder/base/Execute.java
  src/main/java/br/com/rabbithole/core/builder/base/actions/HashWrite.java
  src/main/java/br/com/rabbithole/core/builder/base/actions/Read.java
  src/main/java/br/com/rabbithole/core/builder/base/actions/Write.java
  src/main/java/br/com/rabbithole/core/builder/base/options/CommandOptions.java
  src/main/java/br/com/rabbithole/core/builder/base/options/Options.java
  src/main/java/br/com/rabbithole/core/builder/commands/generics/sets/Set.java
Labels: enhancement

#21 fix(readme): fix code example
  README.md
  src/test/java/TestClass.java
Labels: bug

#23 New hash commands have been implemented
  README.md
  pom.xml
  src/main/java/br/com/rabbithole/core/builder/commands/generics/sets/SetNx.java
  src/main/java/br/com/rabbithole/core/builder/commands/hash/HashGetAll.java
  src/main/java/br/com/rabbithole/core/builder/commands/hash/HashKeys.java
  src/main/java/br/com/rabbithole/core/builder/commands/hash/HashLength.java
  src/main/java/br/com/rabbithole/core/builder/commands/hash/HashSetNx.java
  src/main/java/br/com/rabbithole/core/builder/commands/hash/HashStringLength.java
  src/main/java/br/com/rabbithole/core/builder/commands/hash/HashValues.java
  src/test/java/TestClass.java
Labels: bug, documentation, enhancement

#24 Update README.md
  README.md
Labels: bug
